/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JLabel;

/**
 *
 * @author Michu
 */
public class RatingPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public RatingPanel() {
        initComponents();

    }

    Stars star = new Stars();
    private final int starOneID = 0;
    private final int starTwoID = 1;
    private final int starThreeID = 2;
    private final int starFourID = 3;
    private final int starFiveID = 4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        star1 = new javax.swing.JLabel();
        star2 = new javax.swing.JLabel();
        star3 = new javax.swing.JLabel();
        star4 = new javax.swing.JLabel();
        star5 = new javax.swing.JLabel();

        setName("1"); // NOI18N

        star1.setIcon(star.emptyStar()
        );
        star1.setMaximumSize(new java.awt.Dimension(100, 94));
        star1.setName(""); // NOI18N
        star1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star1MousePressed(evt);
            }
        });

        star2.setIcon(star.emptyStar());
        star2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star2MousePressed(evt);
            }
        });

        star3.setIcon(star.emptyStar());
        star3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star3MousePressed(evt);
            }
        });

        star4.setIcon(star.emptyStar());
        star4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star4MousePressed(evt);
            }
        });

        star5.setIcon(star.emptyStar()
        );
        star5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                star5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                star5MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                star5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(star1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(star2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(star4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(star5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(star3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(star2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(star4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(star5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(star1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                        .addGap(68, 68, 68))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void star1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseEntered
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseEntered(arrayOfLabels, starOneID);
    }//GEN-LAST:event_star1MouseEntered

    private void star1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MouseExited
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseExited(arrayOfLabels);
    }//GEN-LAST:event_star1MouseExited

    private void star3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseEntered
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseEntered(arrayOfLabels, starThreeID);
    }//GEN-LAST:event_star3MouseEntered

    private void star3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MouseExited
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseExited(arrayOfLabels);
    }//GEN-LAST:event_star3MouseExited

    private void star2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseEntered
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseEntered(arrayOfLabels, starTwoID);
    }//GEN-LAST:event_star2MouseEntered

    private void star2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MouseExited
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseExited(arrayOfLabels);
    }//GEN-LAST:event_star2MouseExited

    private void star4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseEntered
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseEntered(arrayOfLabels, starFourID);
    }//GEN-LAST:event_star4MouseEntered

    private void star4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MouseExited
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseExited(arrayOfLabels);
    }//GEN-LAST:event_star4MouseExited

    private void star5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseEntered
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseEntered(arrayOfLabels, starFiveID);
    }//GEN-LAST:event_star5MouseEntered

    private void star5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MouseExited
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mouseExited(arrayOfLabels);
    }//GEN-LAST:event_star5MouseExited

    private void star1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star1MousePressed
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mousePressed(arrayOfLabels, starOneID);
    }//GEN-LAST:event_star1MousePressed

    private void star2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star2MousePressed
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mousePressed(arrayOfLabels, starTwoID);
    }//GEN-LAST:event_star2MousePressed

    private void star3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star3MousePressed
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mousePressed(arrayOfLabels, starThreeID);
    }//GEN-LAST:event_star3MousePressed

    private void star4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star4MousePressed
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mousePressed(arrayOfLabels, starFourID);
    }//GEN-LAST:event_star4MousePressed

    private void star5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_star5MousePressed
        JLabel[] arrayOfLabels = {star1, star2, star3, star4, star5};
        star.mousePressed(arrayOfLabels, starFiveID);
    }//GEN-LAST:event_star5MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel star1;
    private javax.swing.JLabel star2;
    private javax.swing.JLabel star3;
    private javax.swing.JLabel star4;
    private javax.swing.JLabel star5;
    // End of variables declaration//GEN-END:variables

}
